# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0.2.0
_src_path: gh:radio-aktywne/template-app-next
accountname: radio-aktywne
appname: lotus
description: Broadcast playlists app 💽
docs: true
docsurl: https://radio-aktywne.github.io/lotus
envprefix: LOTUS
imagename: apps/lotus
keyprefix: lotus
port: 10230
registry: true
releases: true
reponame: lotus
repourl: https://github.com/radio-aktywne/lotus
